### ISSUE TITLE
Locale settings crash on Windows

### ISSUE THREAD

**Issue by rasmack** [bytesandbrains/statbank-python#1]
In the Data constructor in resources.py, there's a call to

locale.resetlocale()

This causes a crash on Windows as can be seen here:

[https://bugs.python.org/issue37945](url)

The root cause seems to be that Windows does not return a standard two-letter ISO code which is expected from setlocale and its friends.

Commenting out the offending call in resources.py fixes the problem, but I thought I'd report the issue in case removing the line brings up other problems I just hadn't seen yet.

**Comment by zachasme** [comment]
Thanks for posting the issue! As far as I can tell, it doesn't bring up other problems. I'll upload a new version with the fix.
